name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Run tests
        working-directory: server
        run: npm test

  build_image:
    name: Build Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and tag image
        run: |
          docker build \
            --file ./server/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/agileace:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository_owner }}/agileace:latest \
            .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/agileace:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/agileace:latest
